name: ci

on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        react: ["^18.x", "^19.x"]
        script: ["typecheck", "build", "build-storybook"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install packages
        run: yarn --immutable
      - name: Setup react
        run: |
          yarn up react@${{ matrix.react }} react-dom@${{ matrix.react }} @types/react@${{ matrix.react }} @types/react-dom@${{ matrix.react }}
          yarn info --all --name-only react react-dom @types/react @types/react-dom
      - name: Run script
        run: yarn ${{ matrix.script }}
