name: Build and Deploy Storybook
on:
  release:
    types: [published]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install packages
        run: yarn --immutable
      - name: Build packages
        run: yarn build

      - name: Build Storybook
        run: yarn build-storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ./packages/form/storybook-static
